services:
  postgres:
    image: postgres:16
    container_name: onpu-postgres
    environment:
      POSTGRES_DB: onpu
      POSTGRES_USER: onpu
      POSTGRES_PASSWORD: onpu
    ports:
      - "5432:5432"
    volumes:
      - onpu-postgres-data:/var/lib/postgresql/data

volumes:
  onpu-postgres-data:
