/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq.tables;


import com.onpu.jooq.Indexes;
import com.onpu.jooq.Keys;
import com.onpu.jooq.Onpu;
import com.onpu.jooq.tables.Users.UsersPath;
import com.onpu.jooq.tables.records.AnswerLogsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerLogs extends TableImpl<AnswerLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>onpu.answer_logs</code>
     */
    public static final AnswerLogs ANSWER_LOGS = new AnswerLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnswerLogsRecord> getRecordType() {
        return AnswerLogsRecord.class;
    }

    /**
     * The column <code>onpu.answer_logs.id</code>.
     */
    public final TableField<AnswerLogsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>onpu.answer_logs.user_id</code>.
     */
    public final TableField<AnswerLogsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>onpu.answer_logs.mode</code>.
     */
    public final TableField<AnswerLogsRecord, String> MODE = createField(DSL.name("mode"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>onpu.answer_logs.question</code>.
     */
    public final TableField<AnswerLogsRecord, String> QUESTION = createField(DSL.name("question"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>onpu.answer_logs.is_correct</code>.
     */
    public final TableField<AnswerLogsRecord, Byte> IS_CORRECT = createField(DSL.name("is_correct"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>onpu.answer_logs.answered_at</code>.
     */
    public final TableField<AnswerLogsRecord, LocalDateTime> ANSWERED_AT = createField(DSL.name("answered_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private AnswerLogs(Name alias, Table<AnswerLogsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AnswerLogs(Name alias, Table<AnswerLogsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>onpu.answer_logs</code> table reference
     */
    public AnswerLogs(String alias) {
        this(DSL.name(alias), ANSWER_LOGS);
    }

    /**
     * Create an aliased <code>onpu.answer_logs</code> table reference
     */
    public AnswerLogs(Name alias) {
        this(alias, ANSWER_LOGS);
    }

    /**
     * Create a <code>onpu.answer_logs</code> table reference
     */
    public AnswerLogs() {
        this(DSL.name("answer_logs"), null);
    }

    public <O extends Record> AnswerLogs(Table<O> path, ForeignKey<O, AnswerLogsRecord> childPath, InverseForeignKey<O, AnswerLogsRecord> parentPath) {
        super(path, childPath, parentPath, ANSWER_LOGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AnswerLogsPath extends AnswerLogs implements Path<AnswerLogsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AnswerLogsPath(Table<O> path, ForeignKey<O, AnswerLogsRecord> childPath, InverseForeignKey<O, AnswerLogsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AnswerLogsPath(Name alias, Table<AnswerLogsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AnswerLogsPath as(String alias) {
            return new AnswerLogsPath(DSL.name(alias), this);
        }

        @Override
        public AnswerLogsPath as(Name alias) {
            return new AnswerLogsPath(alias, this);
        }

        @Override
        public AnswerLogsPath as(Table<?> alias) {
            return new AnswerLogsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Onpu.ONPU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ANSWER_LOGS_IDX_USER_MODE);
    }

    @Override
    public Identity<AnswerLogsRecord, Long> getIdentity() {
        return (Identity<AnswerLogsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AnswerLogsRecord> getPrimaryKey() {
        return Keys.KEY_ANSWER_LOGS_PRIMARY;
    }

    @Override
    public List<ForeignKey<AnswerLogsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ANSWER_LOGS_IBFK_1);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>onpu.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ANSWER_LOGS_IBFK_1, null);

        return _users;
    }

    @Override
    public AnswerLogs as(String alias) {
        return new AnswerLogs(DSL.name(alias), this);
    }

    @Override
    public AnswerLogs as(Name alias) {
        return new AnswerLogs(alias, this);
    }

    @Override
    public AnswerLogs as(Table<?> alias) {
        return new AnswerLogs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnswerLogs rename(String name) {
        return new AnswerLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnswerLogs rename(Name name) {
        return new AnswerLogs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnswerLogs rename(Table<?> name) {
        return new AnswerLogs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnswerLogs where(Condition condition) {
        return new AnswerLogs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnswerLogs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnswerLogs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnswerLogs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnswerLogs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnswerLogs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnswerLogs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnswerLogs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnswerLogs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnswerLogs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
