/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq;


import com.onpu.jooq.tables.AnswerLogs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_ANSWER_LOGS_USER_MODE = Internal.createIndex(DSL.name("idx_answer_logs_user_mode"), AnswerLogs.ANSWER_LOGS, new OrderField[] { AnswerLogs.ANSWER_LOGS.USER_ID, AnswerLogs.ANSWER_LOGS.MODE }, false);
}
