/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq;


import com.onpu.jooq.tables.AnswerLogs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in onpu.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANSWER_LOGS_IDX_USER_MODE = Internal.createIndex(DSL.name("idx_user_mode"), AnswerLogs.ANSWER_LOGS, new OrderField[] { AnswerLogs.ANSWER_LOGS.USER_ID, AnswerLogs.ANSWER_LOGS.MODE }, false);
}
