/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq;


import com.onpu.jooq.tables.AnswerLogs;
import com.onpu.jooq.tables.Users;
import com.onpu.jooq.tables.records.AnswerLogsRecord;
import com.onpu.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * onpu.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AnswerLogsRecord> KEY_ANSWER_LOGS_PRIMARY = Internal.createUniqueKey(AnswerLogs.ANSWER_LOGS, DSL.name("KEY_answer_logs_PRIMARY"), new TableField[] { AnswerLogs.ANSWER_LOGS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_UK_LOGIN_ID = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_uk_login_id"), new TableField[] { Users.USERS.LOGIN_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AnswerLogsRecord, UsersRecord> ANSWER_LOGS_IBFK_1 = Internal.createForeignKey(AnswerLogs.ANSWER_LOGS, DSL.name("answer_logs_ibfk_1"), new TableField[] { AnswerLogs.ANSWER_LOGS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
}
