/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq;


import com.onpu.jooq.tables.AnswerLogs;
import com.onpu.jooq.tables.Users;
import com.onpu.jooq.tables.records.AnswerLogsRecord;
import com.onpu.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AnswerLogsRecord> ANSWER_LOGS_PKEY = Internal.createUniqueKey(AnswerLogs.ANSWER_LOGS, DSL.name("answer_logs_pkey"), new TableField[] { AnswerLogs.ANSWER_LOGS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_LOGIN_ID_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_login_id_key"), new TableField[] { Users.USERS.LOGIN_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AnswerLogsRecord, UsersRecord> ANSWER_LOGS__ANSWER_LOGS_USER_ID_FKEY = Internal.createForeignKey(AnswerLogs.ANSWER_LOGS, DSL.name("answer_logs_user_id_fkey"), new TableField[] { AnswerLogs.ANSWER_LOGS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
