/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq;


import com.onpu.jooq.tables.AnswerLogs;
import com.onpu.jooq.tables.Users;


/**
 * Convenience access to all tables in onpu.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>onpu.answer_logs</code>.
     */
    public static final AnswerLogs ANSWER_LOGS = AnswerLogs.ANSWER_LOGS;

    /**
     * The table <code>onpu.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
