/*
 * This file is generated by jOOQ.
 */
package com.onpu.jooq.tables.records;


import com.onpu.jooq.tables.AnswerLogs;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerLogsRecord extends UpdatableRecordImpl<AnswerLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>onpu.answer_logs.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>onpu.answer_logs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>onpu.answer_logs.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>onpu.answer_logs.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>onpu.answer_logs.mode</code>.
     */
    public void setMode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>onpu.answer_logs.mode</code>.
     */
    public String getMode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>onpu.answer_logs.question</code>.
     */
    public void setQuestion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>onpu.answer_logs.question</code>.
     */
    public String getQuestion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>onpu.answer_logs.is_correct</code>.
     */
    public void setIsCorrect(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>onpu.answer_logs.is_correct</code>.
     */
    public Byte getIsCorrect() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>onpu.answer_logs.answered_at</code>.
     */
    public void setAnsweredAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>onpu.answer_logs.answered_at</code>.
     */
    public LocalDateTime getAnsweredAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnswerLogsRecord
     */
    public AnswerLogsRecord() {
        super(AnswerLogs.ANSWER_LOGS);
    }

    /**
     * Create a detached, initialised AnswerLogsRecord
     */
    public AnswerLogsRecord(Long id, Long userId, String mode, String question, Byte isCorrect, LocalDateTime answeredAt) {
        super(AnswerLogs.ANSWER_LOGS);

        setId(id);
        setUserId(userId);
        setMode(mode);
        setQuestion(question);
        setIsCorrect(isCorrect);
        setAnsweredAt(answeredAt);
        resetChangedOnNotNull();
    }
}
